// Super C language super mode grammar
//
// W3C's EBNF notation https://www.w3.org/TR/2008/REC-xml-20081126/#sec-notation
// Generate diagram at https://www.bottlecaps.de/rr/ui

SourceFile    ::= TopLevelDecl+

//Declarations
TopLevelDecl  ::= FunctionDecl

FunctionDecl  ::= "fn" FunctionName TypeParameters? Signature TypeConstraints? FunctionBody?
FunctionName  ::= identifier
FunctionBody  ::= Block

//.Type parameter declarations
TypeParameters ::= "$" "(" TypeParameter ("," TypeParemeter)* ")"
TypeParameter  ::= identifer (":" Type)?

TypeConstraints ::= "where" TypeConstraint ("," TypeConstraint)*
TypeConstraint  ::= identifier ":" Type

//Types

//.Function types
FunctionType  ::= "fn" Signature
Signature     ::= Parameters Result?
Result        ::= "->" Type
Parameters    ::= "(" ParameterList? ")"
ParameterList ::= ParameterDecl ("," ParameterDecl)*
ParameterDecl ::= identifier (":" | "::") Type


